usnistgov/dioptra

src/mitre/securingai/generics_plugins/estimator_predict/tf_keras_model.py
src/mitre/securingai/pyplugs/_plugins.py
src/mitre/securingai/restapi/experiment/service.py
src/mitre/securingai/sdk/cryptography/verify.py

Satisfy the new B904 rule (https://github.com/PyCQA/flake8-bugbear/pull/181) from `flake8-bugbear`
by using explicit exception chaining whenever an exception is being transformed.
- use explicit exception chaining

Use explicit chaining when transforming an exception

---

docker/pytorch-cpu/Dockerfile
docker/pytorch-gpu/Dockerfile
docker/tensorflow2-cpu/Dockerfile
docker/tensorflow2-gpu/Dockerfile

- **docker:** install libgl1 in tensorflow and pytorch images

Install missing libgl1 dependency in the Tensorflow and PyTorch images

---

docker/legacy/mlflow-tracking1-12-1/Dockerfile
docker/legacy/restapi-py37/Dockerfile
docker/legacy/tensorflow21-cpu/Dockerfile
docker/mlflow-tracking/Dockerfile
docker/nginx/Dockerfile
docker/pytorch-cpu/Dockerfile
docker/pytorch-gpu/Dockerfile
docker/restapi/Dockerfile
docker/tensorflow2-cpu/Dockerfile
docker/tensorflow2-gpu/Dockerfile
mypy.ini

This fix addresses three issues that caused container image builds to fail:
1. Including ZScaler_Root.crt in the container's certificate chain resolves an issue where MITRE devs were unable to build Dioptra containers on their local machine. This is a temporary workaround.
2. Tools like wget and curl will fail to download Miniconda from repo.continuum.io if OpenSSL v3 is installed, which is the default version of OpenSSL on Ubuntu 22.04. Updating these URLs to the repo.anaconda.com target resolves this issue.
3. Tools like wget and curl will sometimes fail when downloading the AWS CLI zip archive on Ubuntu 22.04. This is due to the upgrade to OpenSSL v3 and because some of the download mirrors for this file point to servers that are not compatible with OpenSSL v3's defaults. Pinning the …

Fix container build failures due to release of Ubuntu 22.04

---

src/dioptra/restapi/task_plugin/controller.py
src/dioptra/restapi/task_plugin/service.py
tests/unit/restapi/task_plugin/conftest.py
tests/unit/restapi/task_plugin/test_service.py

There are only two namespaces for the task plugins, `dioptra_builtins` and `dioptra_custom`. By
passing these explicitly, the service no longer needs to fetch a full list of directories for the Dioptra plugins bucket before fetching the list of plugin files. This allows the service to operate without needing full ListBucket permissions.
This commit also updates the associated `get_all` unit test to reflect the change and removes the stubbed S3 response that is no longer used.

Refactor get_all task plugins function to require fewer S3 permissions

---

examples/tensorflow-adversarial-patches/demo-fruits360-patches.ipynb
examples/tensorflow-adversarial-patches/demo-imagenet-patches.ipynb

This change updates the ipython demos for adversarial patches (Fruits360, ImageNet demos). 
Correction includes an update to adversarial training for the Fruits360 demo and a bugfix for the ImageNet demo.

fix: correct adversarial patch demo run parameters

---

.flake8

chore: blacklist b907 for flake8 settings

---

docs/source/user-guide/api-reference-restapi.rst
src/dioptra/restapi/routes.py
tests/unit/restapi/conftest.py

The user endpoint will support authorization and access controls that are planned for development. The user accounts managed via this endpoint have no functionality at present and so they are being unregistered to avoid confusion.

Unregister the inactivate restapi user endpoint

---

src/dioptra/sdk/utilities/logging/log_stream.py

The classes StdoutLogStream, StderrLogStream subclassed from an abstract class without implementing all methods, causing an error when running the example notebooks. Added implementations to the classes to fix.

bug: logstream classes throw abstract method errors

---

.github/pip-envs/requirements-sphinx.txt

Workaround for breakage introduced in pydata-sphinx-theme 0.13.2, see the discussion at
https://github.com/executablebooks/sphinx-book-theme/issues/711.

ci: pin pydata-sphinx-theme to 0.13.1

---

.gitignore
docs/source/getting-started/building-the-containers.rst

Small typo in the instructions for the make target to build the tensorflow worker containers. See #165

chore: fix typo in getting-started/building-the-containers.rst

---

src/dioptra/restapi/experiment/model.py
src/dioptra/restapi/experiment/schema.py
src/dioptra/restapi/experiment/service.py
src/dioptra/restapi/job/model.py
src/dioptra/restapi/job/schema.py
src/dioptra/restapi/queue/model.py
src/dioptra/restapi/queue/schema.py
src/dioptra/restapi/utils.py
tests/unit/restapi/experiment/test_service.py

Add the slugifiy helper function and use it on strings passed to the database to prevent misses since all names are slugified on registration.
Closes #71

fix(restapi): change service.py to slugify db queries

---

cookiecutter-templates/cookiecutter-dioptra-deployment/cookiecutter.json

The MinIO mc client received a breaking change in March 2023 that deprecated and removed the `mc admin policy add` and `mc admin policy set` commands, which broke the init-minio.sh script in the cookiecutter-dioptra-deployment template. For the short term, the template will pin the minio mc image to a version before the commands were deprecated and removed. The pinning will be relaxed once a longer-term fix to use the new commands is incorporated into init-minio.sh. For additional information, see https://min.io/docs/minio/linux/reference/minio-mc-admin/mc-admin-policy.html.
Closes #189

fix: pin the minio mc client to resolve init-minio.sh script error

---

examples/scripts/venvs/examples-setup-requirements.txt
pyproject.toml
tox.ini

Cookiecutter 2.2.0 is resulting in breakage. This is a temporary measure until a fix is found.

Pin the upper version limit of the cookiecutter package

---

examples/README.md
examples/scripts/register_task_plugins.py

Closes #199 
During refactoring, custom plugins frequently had to be deleted and re-uploaded manually. This adds `-f` and  `--force` flags to `/examples/scripts/register_task_plugins.py` which deletes and reuploads all custom task plugins in order to remove this pain point.

feat: add reloading to plugin script

---

docs/source/user-guide/api-reference-client.rst
src/dioptra/client/__init__.py
src/dioptra/client/__version__.py
src/dioptra/client/_client.py

Towards Resolving #210 
- document the dioptra client class
- move to dioptra.client namespace
- began refactors of examples, pending PR #215 and #202

Formalize the Dioptra Client

---

.github/workflows/tox-tests.yml
cookiecutter-templates/cookiecutter-dioptra-deployment/hooks/post_gen_project.py
src/dioptra/restapi/task_plugin/service.py
tests/cookiecutter_dioptra_deployment/test_create_template.py
tests/unit/task_plugins/dioptra_builtins/artifacts/test_mlflow.py

fixes #248 
This PR addresses an issue where S3 key prefixes followed the platform's path conventions causing tests that validate S3 URIs to fail. The fix is to normalize S3 prefixes to follow POSIX path conventions using `Path.as_posix()` from `pathlib`.
This PR also adds a github action for unit tests on a `windows-2022` image. `test_mlflow.py` was updated to use `pathlib` instead of `os.path` to fix cross-platform issues with the tests.
The cookiecutter tests are disabled for the `windows-2022` runner because those tests depend on a english words file for generating random passwords that does not exist on windows systems. Consider opening a new issue to address this.

fix: Platform specific prefixes

---

docker/shellscripts/entrypoint-worker.m4
src/dioptra/mlflow_plugins/dioptra_clients.py
src/dioptra/restapi/job/controller.py
src/dioptra/restapi/job/dependencies.py
src/dioptra/restapi/job/errors.py
src/dioptra/restapi/job/schema.py
src/dioptra/restapi/job/service.py
src/dioptra/restapi/shared/rq/service.py
src/dioptra/rq/tasks/__init__.py
src/dioptra/rq/tasks/run_task_engine.py
src/dioptra/sdk/utilities/paths/clear_dir.py
src/dioptra/sdk/utilities/s3/__init__.py
src/dioptra/sdk/utilities/s3/download.py
src/dioptra/sdk/utilities/s3/uri.py
src/dioptra/task_engine/run_experiment.py
src/dioptra/task_engine/task_engine.py
src/dioptra/worker/__init__.py
src/dioptra/worker/setup_task_plugins.py
src/dioptra/worker/setup_task_plugins_cli.py
tests/unit/restapi/conftest.py
tests/unit/rq/tasks/test_run_task_engine.py
tests/unit/sdk/utilities/paths/test_clear_directory.py
tests/unit/task_engine/test_task_engine.py

Partially addresses #213 .
This PR adds a function which can be called through redis queue, to cause an experiment to run via the task engine.  In that way, it achieves task engine integration with a worker: you just have to queue the job up a bit differently.
The REST API and UI/frontend aspects of the issue are not addressed here.

Task engine integration into worker containers

---

src/dioptra/restapi/experiment/controller.py
src/dioptra/restapi/experiment/schema.py
src/dioptra/restapi/experiment/service.py
src/dioptra/restapi/job/service.py
tests/unit/restapi/test_experiment.py

Continues the refactor for #312, breaking up the functionality of the Experiment service into different classes. 
Should be merged after PR #339 and #328, will fail unit tests and mypy checks until then.

Refactor experiments endpoint to breakup functionality

---

src/dioptra/restapi/job/controller.py
src/dioptra/restapi/job/errors.py
src/dioptra/restapi/job/schema.py
src/dioptra/restapi/job/service.py
tests/unit/restapi/job/test_controller.py
tests/unit/restapi/job/test_service.py
tests/unit/restapi/test_experiment.py

Refactors the job endpoint to split up functionality of name and id requests. Includes minor changes to the unit tests to reflect those changes.  Resolves #313 
- split by name functionality into a sperate service class
- merge submit and create into one function called create
- remove inline type annotations
- add docstrings to service class
- remove and unit tests for deprecated functions

Refactor jobs restapi to split up id and name functionality

---

src/dioptra/restapi/queue/controller.py
src/dioptra/restapi/queue/schema.py
src/dioptra/restapi/queue/service.py
tests/unit/restapi/test_queue.py

There were a few stray places in the controller layer in the queue endpoint that had calls to slugify instead of being in the service layer. In addition some methods in the service layer like queue locks were not slugifying their name reference. This PR cleans that up, and slugifyies every name reference in the service layer.

Refactor: Move slugify calls to service layer

---

.github/workflows/docker-images.yml

The amount of storage space provided in the GitHub Action runners has been reduced by about 10G. As a result, the GPU Docker image builds are no longer viable on GitHub Actions and so they need to be disabled.

Disable GPU image builds in GitHub Actions

---

src/dioptra/restapi/v1/schemas.py

The body of `generate_base_resource_schema` now imports reference schemas in the body of the function. All schemas will typically import from the base schema, and the base schema imports some reference schemas. This can result in a circular import if done at the top of the file. Moving to the body of the relevant function resolves this issue.

refactor: move imports to body of generate_base_resource_schema to avoid circular imports

---

cookiecutter-templates/cookiecutter-dioptra-deployment/{{cookiecutter.__project_slug}}/config/nginx/http_minio.conf
cookiecutter-templates/cookiecutter-dioptra-deployment/{{cookiecutter.__project_slug}}/config/nginx/https_minio.conf

Fixes #346 .
I think that the reason for the error is that both client and server (minio in our case) create a signature from a http request, based on certain request headers.  The client's signature is transmitted to the server in yet another header.  The server computes its own signature based on the request it received and compares to the signature received from the client.  If they don't match, the request is rejected.
This means that certain headers are critical for S3 to work: if nginx alters them as it proxies, it alters the resulting signature and causes minio to reject the request.  The problematic header in this case seems to be the `Host` header.  The fix in this PR alters the nginx config for minio to pass along the Host header.  It seems to work for me in the non-TLS case (I …

fix: Add Host header setting to nginx config for minio.

---

tests/conftest.py

This feature adds a `--run-v1` flag to pytest in `tests/conftest.py` to enable running of v1 API tests. To mark a test as v1, annotate the test function with `@pytest.mark.v1`.
We intend to use this feature during the development of v1 of the API. Tests are expected to fail while the service layer is not implemented so they should be excluded by default.
v1 tests should be placed in the `restapi/v1` directory.
To run only v1 tests use the command below:
```
python -m tox run -e py39-pytest -- tests/unit/restapi/v1 --run-v1
```

feat: add pytest flag to run v1 REST API tests

---

src/dioptra/restapi/routes.py
src/dioptra/restapi/v1/auth/__init__.py
src/dioptra/restapi/v1/auth/controller.py
src/dioptra/restapi/v1/auth/schema.py

This feature adds the request and response marshmallow schemas for the `/auth` resource. It also includes stub functions for the controller layer that defines the `/auth` endpoints as well as register these routes in the v1 API namespace.

feat: add schema and controller stubs for Authentication endpoint

---

src/dioptra/restapi/routes.py
src/dioptra/restapi/v1/models/__init__.py
src/dioptra/restapi/v1/models/controller.py
src/dioptra/restapi/v1/models/schema.py

This is blocked until #410 is merged. Also include model schemas and endpoints for version endpoints that are not in the original API map.

feat: implement v1 schemas for models

---

src/dioptra/restapi/v1/groups/controller.py
src/dioptra/restapi/v1/groups/schema.py

This feature adds an endpoint for updating all user permissions for a group to the v1 REST API. This is implemented via a PUT to `/groups/{id}/members`. It includes the necessary changes to the groups schema and controller layer.
This commit also includes some minor changes to the group's schema that do not change functionality. This includes moving an import nested inside of a class and a nested class definition to the top level.

feat: add batch permissions changes to groups

---

src/dioptra/restapi/v1/experiments/controller.py
src/dioptra/restapi/v1/jobs/controller.py

This features modifies how jobs are handled in the REST API. Since Jobs can only be created as part of an experiment, the POST has been moved to /experiments/{id}/jobs. The GETs and DELETE associated with a specific Job have been replicated under /experiments/{id}/jobs because Job operations will often be performed within the context of an Experiment.

feat: updated v1 API for changes to Experiments and Jobs

---

src/dioptra/restapi/v1/artifacts/schema.py
src/dioptra/restapi/v1/auth/controller.py
src/dioptra/restapi/v1/auth/schema.py
src/dioptra/restapi/v1/entrypoints/schema.py
src/dioptra/restapi/v1/experiments/schema.py
src/dioptra/restapi/v1/groups/controller.py
src/dioptra/restapi/v1/groups/schema.py
src/dioptra/restapi/v1/jobs/schema.py
src/dioptra/restapi/v1/models/schema.py
src/dioptra/restapi/v1/plugins/controller.py
src/dioptra/restapi/v1/plugins/schema.py
src/dioptra/restapi/v1/queues/controller.py
src/dioptra/restapi/v1/queues/schema.py

This feature updates the marshmallow schemas for the v1 REST API to indicate required fields and provide default values for optional fields.
Forced type conversions were removed from the controller layers to avoid incorrect conversions for optional fields.

feat: updated schemas to indicate required and optional fields

---

src/dioptra/restapi/db/models/plugins.py
src/dioptra/restapi/v1/plugins/controller.py
src/dioptra/restapi/v1/plugins/errors.py
src/dioptra/restapi/v1/plugins/service.py
src/dioptra/restapi/v1/utils.py
tests/unit/restapi/lib/actions.py
tests/unit/restapi/v1/conftest.py
tests/unit/restapi/v1/test_plugin.py

This commit updates the PluginIdFileService and PluginIdFileIdService classes in the service layer with support for plugin tasks. Plugin tasks can be registered when a new PluginFile object is created or added by modifying an existing PluginFile to include them. Additional changes that were made to implement the plugin task functionality include:
- Configuring several plugin ORM relationships with the `lazy="joined"` setting to ensure the related data is eagerly pulled and cached at query time. Existing queries that retrieved multiple PluginFile objects had to have the `.unique()` method appended to them.
- Creating helper functions for constructing PluginTask ORM objects and adding them to the database.
- Adding support to existing helper functions for processing PluginFile data …

Implement plugin task registration in plugin file sub-endpoints

---

src/dioptra/restapi/errors.py
src/dioptra/restapi/v1/entrypoints/controller.py
src/dioptra/restapi/v1/entrypoints/errors.py
src/dioptra/restapi/v1/entrypoints/schema.py
src/dioptra/restapi/v1/entrypoints/service.py
src/dioptra/restapi/v1/experiments/service.py
src/dioptra/restapi/v1/plugins/controller.py
src/dioptra/restapi/v1/plugins/service.py
src/dioptra/restapi/v1/queues/service.py
src/dioptra/restapi/v1/schemas.py
src/dioptra/restapi/v1/shared/snapshots/controller.py
src/dioptra/restapi/v1/utils.py
tests/unit/restapi/lib/actions.py
tests/unit/restapi/lib/asserts.py
tests/unit/restapi/v1/conftest.py
tests/unit/restapi/v1/test_entrypoint.py
tests/unit/restapi/v1/test_experiment.py
tests/unit/restapi/v1/test_group.py
tests/unit/restapi/v1/test_plugin_parameter_type.py

This feature adds an implementation of the service layer for v1 of the REST API for the Entrypoints
endpoint. It includes the Tags, ResourceDrafts, and ResourceSnapshots (versions) subendpoints. as
well as search functionality. This commit also includes unit tests that cover common user
interactions with Entrypoints.
The primary implementations are in `restapi/entrypoints/service.py`. The services are injected into
controller layer in `restapi/entrypoints/controller.py` which calls the appropriate service layer
functionality. The controller layer uses helper functions from `restapi/utils.py` to translate ORM
objects back to the response types expected by the schema. Error handling is added to v1 routes by
registering error handlers in `restapi/errors.py`.

feat: entrypoints service layer

---

src/dioptra/restapi/v1/shared/drafts/controller.py
src/dioptra/restapi/v1/utils.py

This feature serializes the contents of the draft payload using the resources schema before returning to the user. This ensures consistent field names in the payload for the user.

feat: serialize draft payload with resource schema

---

src/dioptra/restapi/db/alembic/versions/d2bae5f6d991_add_readonly_resource_locks_to_pre_.py
src/dioptra/restapi/v1/plugin_parameter_types/errors.py
src/dioptra/restapi/v1/plugin_parameter_types/service.py
src/dioptra/restapi/v1/users/service.py
tests/unit/restapi/lib/actions.py
tests/unit/restapi/v1/conftest.py
tests/unit/restapi/v1/test_plugin_parameter_type.py

This update makes it so that the 6 built-in plugin task parameter types, "any", "number", "integer", "string", "boolean", and "null", are automatically registered and protected with a readonly lock immediately after the default public group is created (currently, this happens when the first user account is created). The plugin parameter types endpoint has been updated to prevent users from creating new plugin parameter types with case-insensitive names that match the built-in types. The endpoint has also been updated to check for the presence of the readonly lock to prevent modification in PUT requests.
In addition, an alembic migration script has been added that:
1. Scans the database for existing parameter types that match the built-ins and sets a read-only lock on them.
2. Checks if …

Auto-register and protect built-in plugin task parameter types

---

src/dioptra/restapi/v1/experiments/controller.py
src/dioptra/restapi/v1/experiments/schema.py
src/dioptra/restapi/v1/experiments/service.py
src/dioptra/restapi/v1/utils.py
tests/unit/restapi/lib/actions.py
tests/unit/restapi/v1/test_experiment.py

feat: add search, tags, drafts, and snapshots to Experiments
This feature adds the following funcionality to Experiments:
- search by name, description, or tag
- ability to manage (retriev, apply, and remove) tags
- ability to create drafts
- the ability to view the history of resource

feat: add search, drafts, snapshots, and tags to Experiments

---

src/dioptra/restapi/v1/entrypoints/controller.py
src/dioptra/restapi/v1/experiments/controller.py
src/dioptra/restapi/v1/schemas.py
src/dioptra/restapi/v1/shared/drafts/controller.py
src/dioptra/restapi/v1/shared/drafts/service.py
src/dioptra/restapi/v1/shared/snapshots/controller.py

This PR includes the following fixes:
fix: set custom schema names to avoid name clashes in swagger
This commit sets custom schema model names in generated subendpoint
Resource classes. flask accepts autogenerates these names by default,
but name clashes can occur when variations of a schema are used across
different endpoints (e.g. when using exclude to remove a field), which
was causing incorrect documentation in swagger.
fix: exclude groupId from draft schema where it should be inferred
fix: make group required in base resource load schema

V1 schema fixes

---

.gitignore
src/dioptra/restapi/routes.py
src/dioptra/restapi/v1/workflows/__init__.py
src/dioptra/restapi/v1/workflows/controller.py
src/dioptra/restapi/v1/workflows/errors.py
src/dioptra/restapi/v1/workflows/lib/__init__.py
src/dioptra/restapi/v1/workflows/lib/export_plugin_files.py
src/dioptra/restapi/v1/workflows/lib/export_task_engine_yaml.py
src/dioptra/restapi/v1/workflows/lib/package_job_files.py
src/dioptra/restapi/v1/workflows/lib/views.py
src/dioptra/restapi/v1/workflows/schema.py
src/dioptra/restapi/v1/workflows/service.py

This update implements the workflows/jobFilesDownload endpoint, which allows users to download a pre-packaged version of the job files needed to run a Dioptra job using the task engine. Retrieving the files requires users to issue a GET request to /workflows/jobFilesDownload, and provide the previously created job id and the desired file type as query parameters.

Add the workflows/jobFilesDownload API endpoint

---

MANIFEST.in
pyproject.toml
src/dioptra/restapi/bootstrap.py
src/dioptra/restapi/db/models/entry_points.py
src/dioptra/restapi/utils.py
src/dioptra/restapi/v1/jobs/service.py
src/dioptra/restapi/v1/shared/rq_service.py
src/dioptra/restapi/v1/workflows/errors.py
src/dioptra/restapi/v1/workflows/lib/export_job_parameters.py
src/dioptra/restapi/v1/workflows/lib/export_run_dioptra_job_script.py
src/dioptra/restapi/v1/workflows/lib/export_task_engine_yaml.py
src/dioptra/restapi/v1/workflows/lib/package_job_files.py
src/dioptra/restapi/v1/workflows/lib/run_dioptra_job.py.tmpl
src/dioptra/restapi/v1/workflows/lib/views.py
src/dioptra/restapi/v1/workflows/service.py
src/dioptra/rq/tasks/__init__.py
src/dioptra/rq/tasks/run_v1_dioptra_job.py
src/dioptra/sdk/utilities/contexts/_sys_path_dirs.py
src/dioptra/worker/dioptra_worker_v1.py
tests/unit/restapi/conftest.py
tests/unit/restapi/lib/mock_rq.py
tests/unit/restapi/v1/conftest.py
tests/unit/restapi/v1/test_job.py

This commit adds the necessary functionality so that when Dioptra users create a Job, the defined job will be submitted to a Redis-based queue for execution. The queued job is then picked up by a worker process, which downloads the job files using the /workflows/jobFilesDownload endpoint and runs the job they define.
The contents of the downloaded tarfile/zipfile obtained via /workflows/jobFilesDownload has been updated to now include a run_dioptra_job.py script and a parameters.json file (these are the parameters set at job submission time). The script + parameters.json + task engine YAML + plugins directory, all of which are included in the tarfile, fully define the job that needs to be executed. The result is that the logic for the Dioptra v1 worker process is light-weight. It only …

Integrate Redis queue and add Dioptra V1 Worker functions

---

src/dioptra/restapi/v1/experiments/controller.py
src/dioptra/restapi/v1/jobs/controller.py
src/dioptra/restapi/v1/jobs/errors.py
src/dioptra/restapi/v1/jobs/schema.py
src/dioptra/restapi/v1/jobs/service.py

This commit adds the MlflowRun endpoint to Jobs. It contains functionality to get and set the MlflowRun ID for a job. The endpoint is nested under `/experiments/{id}/jobs/{jobId}/mlflowRrun`. The id can be set via a POST and retrieved via a GET. Once set, the id cannot be changed and the API will return a 400 BAD REQUEST error. Setting the mlflow run id does not create a new snapshot or change the last modified on timestamp.

feat: add MlflowRun endpoint to Jobs

---

src/dioptra/restapi/v1/workflows/lib/run_dioptra_job.py.tmpl
src/dioptra/rq/tasks/run_v1_dioptra_job.py

This commit updates the worker and job execution scripts to set the mlflow run id when the mlflow tracking capability is enabled.

Update worker and job execution scripts to set mlflow run id

---

src/dioptra/restapi/v1/experiments/service.py
tests/unit/restapi/v1/test_entrypoint.py

This commit fixes a bug where retrieving an experiment that was associated with an entrypoint that has since been deleted resulted in a 404 error. The issue was that the experiment get methods did not check for a delete lock on the entrypoint objects.
This fix resolves the issue by:
- Adding deletion checks when retrieving entrypoints associated with an experiment
- Updating the entrypoint deletion test assert an associated experiment can be retrieved and the deleted entrypoint is no longer listed.

fix: entrypoint deletion now removes association with experiments

---

cookiecutter-templates/cookiecutter-dioptra-deployment/cookiecutter.json

This commit changes the default Compose command in the cookiecutter config from the deprecated `docker-compose` to the modern Compose plugin command, `docker compose`.
closes #552

fix: update default docker compose command in cookiecutter template

---

src/dioptra/restapi/v1/shared/drafts/controller.py

This fixes #547 by raising an error if the specified draft doesn't exist. The swagger docs now correctly report a 404 not found error when attempting to modify a draft that doesn't exist. This issue (and fix) applies to drafts for all applicable endpoints.

fix: resolve internal server error when modifying nonexistent draft

---

cookiecutter-templates/cookiecutter-dioptra-deployment/cookiecutter.json

The tag for the `argbash` docker container set within cookiecutter.json is currently set to `sha-0d046a`, which doesn't exist and causes a build failure. This PR updates to `sha-0d046ad`, which is a valid tag.
Before fix: 
After fix: 
Maintainers: double check `matejak/argbash:sha-0d046ad` is the intended version from the [argbash Docker Hub repo](https://hub.docker.com/r/matejak/argbash/tags).

Fix build-breaking typo in cookiecutter.json

---

src/dioptra/restapi/v1/utils.py

The API was returning the snapshot's created_on timestamp instead of the resource's created_on timestamp. This commit fixes the issue in the response build functions in `restapi/v1/utils.py`.

fix: return correct createdOn timestamp for all resources

---

src/dioptra/task_engine/error_message.py
tox.ini

An alternative to the fix from ffeb0a2.
The pypi page for `types-jsonschema` says [1]:
> ... aims to provide accurate annotations for jsonschema==4.23.*
But additional typing information was also added to the `jsonschema` library in 4.23.  I don't really understand how all the typing information interacts, but the aforementioned pypi docs imply we still need the typestub library.  Having the library also resolves the typing error for the return value of `_is_valid_for_sub_schema`, which is something I had fixed (i.e. removal of the library actually seemed to "unfix" it).
The github action errors were:
```
src/dioptra/task_engine/error_message.py:283:47: error: Argument 1 to "_get_one_of_alternative_names" has incompatible type "Any | Unset"; expected "Iterable[Any]"  [arg-type] …
```

fix: an alternative fix for a mypy type error in error_message.py

---

src/frontend/src/components/LoginForm.vue
src/frontend/src/components/NavBar.vue

When a user is not logged in, all requests should redirect to the login page. Additionally, the navigation tabs along the top should be hidden until the user logs in.

feat: redirect to login when logged out

---

src/dioptra/restapi/v1/utils.py
tests/unit/restapi/v1/test_plugin.py

This commit fixes an issue where plugin task parameters were returned sorted alphabetically by name instead of respecting the specified order. It modifies an existing test to check for this case.

fix: incorrect plugin task parameter order

---

src/frontend/src/dialogs/AssignTagsDialog.vue

When creating a new tag in the assign tags dialog, it should be selected by default.  You still need to hit confirm to save the selection.

feat: select tag upon create

---

src/frontend/src/views/CreatePluginFile.vue

The Plugin Param Types table in the PluginFile form is too prominent.  This PR hides that table in an expandable row.  The table is collapsed by default, and user can click on `Show Plugin Param Types` to expand.

feat: hide param types in expandable row

---

src/dioptra/restapi/db/alembic/versions/6a75ede23821_update_entry_point_parameter_types_list.py
src/dioptra/restapi/v1/entrypoints/schema.py
src/dioptra/restapi/v1/workflows/lib/export_job_parameters.py
src/dioptra/restapi/v1/workflows/lib/export_task_engine_yaml.py
src/dioptra/restapi/v1/workflows/lib/package_job_files.py
src/dioptra/restapi/v1/workflows/lib/run_dioptra_job.py.tmpl
src/dioptra/restapi/v1/workflows/lib/type_coercions.py
src/dioptra/restapi/v1/workflows/lib/views.py
src/dioptra/restapi/v1/workflows/service.py
src/dioptra/rq/tasks/run_v1_dioptra_job.py
src/dioptra/sdk/utilities/contexts/__init__.py
src/dioptra/sdk/utilities/contexts/_env_vars.py
src/frontend/src/dialogs/EditParamDialog.vue
src/frontend/src/views/CreateEntryPoint.vue
tests/unit/restapi/lib/db/setup.py
tests/unit/restapi/v1/conftest.py

**Request: Please do not squash, rebase and merge to dev only.** The commits are different enough in scope and purpose that squashing will obscure the reasons for the various updates.
The first commit adds support for the "boolean", "integer", "list", and "mapping" entrypoint parameter types that are already supported by the task execution engine. In addition, the `/workflows/jobFilesDownload` endpoint service has been updated to handle all supported types when creating the parameters.json and task engine YAML files. The "path" and "uri" types have been removed since they were treated the same as strings.
The second commit adds the `env_vars` contextmanager to the Dioptra SDK, which can be used to temporarily update environment variables in a safe and reversible way.
The third commit …

Update the list of supported entrypoint parameter types and add workaround to export full list of plugin parameter types

---

.gitignore
src/frontend/package-lock.json
src/frontend/package.json
src/frontend/src/components/CodeEditor.vue
src/frontend/src/services/dataApi.ts
src/frontend/src/views/CreateEntryPoint.vue

This PR adds a plugin task table to the entrypoints form.  Each task has an `Add to Task Graph` button which adds the appropriate YAML to the task graph in a new line.  The entrypoint needs to have plugins that have files with tasks in order for the table to be populated.

feat: insert into task graph button

---

src/frontend/src/components/TableComponent.vue
src/frontend/src/dialogs/AssignPluginsDialog.vue
src/frontend/src/dialogs/AssignTagsDialog.vue
src/frontend/src/services/dataApi.ts
src/frontend/src/views/CreateEntryPoint.vue
src/frontend/src/views/CreateExperiment.vue
src/frontend/src/views/CreateJob.vue
src/frontend/src/views/CreatePluginFile.vue

This PR adds the ability for the frontend to "get all" data from a GET endpoint, by hitting the `next` url until there is no `next`, and return all the aggregated data.
This fixes the issue where menu selections (such as the assign tags dialog or the various queues, plugins, entrypoint dropdowns) only gets the first "page" of results instead of all results.
This also allows all tables to have an "All" option for rows-per-page.

get all data

---

src/frontend/src/views/CreateEntryPoint.vue

The plugins dropdown in the entrypoints form wasn't properly pulling in the Plugin Tasks in the table.  This is because when calling getting files for each plugin, it wasn't passing in the needed pagination values that all GET requests need.

fix: plugins dropdown in entrypoints form fix

---

src/frontend/src/components/CodeEditor.vue
src/frontend/src/views/EntryPointsView.vue

Issue: https://github.com/usnistgov/dioptra/issues/564
In the entrypoints table, the code editor in the "View YAML" popup and the expanded row should be readonly.  This was working previously but got broken again somehow.  This PR fixes it using a disabled prop.

fix: yaml in entrypoints table should be readonly

---

docker/shellscripts/healthcheck-worker.m4

Suggested fix for #476. Reports healthy for the worker containers when the worker process is running. Since the containers automatically restart if the worker process is stopped, a cloned image with a dummy entrypoint was used to test the unhealthy state. After startup with no worker process running, the unhealthy state was properly reported.

fix: update worker health check

---

src/dioptra/client/experiments.py
src/dioptra/client/jobs.py
src/dioptra/restapi/errors.py
src/dioptra/restapi/v1/experiments/controller.py
src/dioptra/restapi/v1/experiments/schema.py
src/dioptra/restapi/v1/jobs/controller.py
src/dioptra/restapi/v1/jobs/schema.py
src/dioptra/restapi/v1/jobs/service.py
src/dioptra/restapi/v1/utils.py
tests/unit/restapi/lib/actions.py
tests/unit/restapi/lib/asserts.py
tests/unit/restapi/lib/mock_mlflow.py
tests/unit/restapi/test_utils.py
tests/unit/restapi/v1/conftest.py
tests/unit/restapi/v1/test_job.py

Closes #671.
Additionally:
Fixes some incorrect function descriptions.
Fixes some mypy linting issues in related files.
Adds a restapi test for the /jobs/{id}/mlflowRun endpoint using a fixture added to help the metrics test.

feat(restapi): add metrics capabilities to RESTAPI

---

src/frontend/src/dialogs/AppendResource.vue
src/frontend/src/router/index.ts
src/frontend/src/services/dataApi.ts
src/frontend/src/views/AllJobsView.vue
src/frontend/src/views/CreateJob.vue

Issue: https://github.com/usnistgov/dioptra/issues/620
- Jobs can now be created through the all-jobs page and the experiment -> job page.
- Entrypoint dropdown will be greyed out until experiment is selected, and will only show entrypoints that are linked to the selected experiment
- Queue dropdown will be greyed out until entrypoint is selected, and will only show queues that are linked to the selected entrypoint
- Returning to an unsaved form should give you the option to load previous values

feat: new common job form

---

src/dioptra/restapi/v1/schemas.py
src/dioptra/restapi/v1/utils.py
tests/unit/restapi/lib/asserts.py
tests/unit/restapi/v1/test_artifact.py
tests/unit/restapi/v1/test_entrypoint.py
tests/unit/restapi/v1/test_experiment.py
tests/unit/restapi/v1/test_job.py
tests/unit/restapi/v1/test_model.py
tests/unit/restapi/v1/test_plugin.py
tests/unit/restapi/v1/test_plugin_parameter_type.py
tests/unit/restapi/v1/test_queue.py

This commit adds the snapshot_created_on datetime field to all Resource response schemas. It also updates the `build_` helper functions to include the field in responses and updates the test suite to validate the updated response schemas.

feat: add snapshot_created_on field to resource response schemas

---

src/frontend/src/dialogs/DialogComponent.vue
src/frontend/src/dialogs/QueueDialog.vue
src/frontend/src/services/dataApi.ts

In the edit queue dialog, add view history toggle to browse snapshots.  Latest snapshot will be selected by default.  Click or tab over to the list, and then you can use up/down arrow keys.  Submit button will be disabled when viewing history.
Timestamps are currently all the same because snapshots inherit timestamp from the parent resource, this will be fixed separately.

feat: browse queue history

---

src/dioptra/client/__init__.py
src/dioptra/client/base.py
src/dioptra/client/sessions.py
src/dioptra/client/utils.py
tests/unit/client/test_utils.py
tests/unit/restapi/lib/client.py

Addresses client-side solution for #694 
Added requests-toolbelt as a new project dependency to support streaming of multi-file uploads.
This branch does not include any new unit tests for this new functionality, as it will start being exercised via the REST API integration tests once we integrate the solutions for #694 with #658. However, in the interest of verifying this new feature for the client works, I created this branch, https://github.com/usnistgov/dioptra/tree/test-client-uploading-support, that adds a simple `/echoes` endpoint that allows you to upload files, and the server echoes back the name and size of the files you upload. I tested it locally and I also created two simple REST API integration tests based on this endpoint to validate the test client implementation. Both …

Add standard interface for handling file uploads in the Dioptra client

---

src/dioptra/restapi/app.py
src/dioptra/restapi/patches.py

This change introduces a monkey-patch for the flask-restx `Swagger.serialize_operation` method to force Swagger to use "multipart/form-data" content type for multi-file uploads instead of "application/x-www-form-urlencoded", as required by our application. The patch applies the proposed changes from PR 542 in the flask-restx repository (https://github.com/python-restx/flask-restx/pull/542), which is unlikely to be accepted into the main branch.
The monkey-patch includes the following safety measures:
- A hash verification system that checks the source code of `flask_restx.Swagger.serialize_operation` before applying the patch. This prevents potential issues if the underlying library code changes.
- Early exit logic that detects if the patch has already been applied, preventing …

[FIX] Add monkey-patch for flask-restx swagger multipart form support

---

src/dioptra/restapi/custom_schema_fields.py
src/dioptra/restapi/utils.py

This update adds a new Marshmallow Schema Field type to handle scenarios where multiple files need to be uploaded through the REST API. The changes include:
- A new MultiFileUpload field class in custom_schema_fields.py
- An update to the parameter schema generation logic that sets the "action" parameter to "append" when the field type is MultiFileUpload.
- A new entry for the MultiFileUpload type in the TYPE_MAP_MA_TO_REQPARSE dictionary, mapping it to werkzeug's FileStorage type.

Add a MultiFileUpload custom Marshmallow Schema Field type

---

src/dioptra/restapi/v1/plugins/schema.py
tests/unit/restapi/v1/test_plugin.py

Fixed bug where API would not except plugin filenames as a directory and added test to support.

Fix folder spec for plugin filename regex

---

src/dioptra/client/drafts.py
src/dioptra/client/entrypoints.py
src/dioptra/client/experiments.py
src/dioptra/client/models.py
src/dioptra/client/plugin_parameter_types.py
src/dioptra/client/plugins.py
src/dioptra/client/queues.py
src/dioptra/restapi/errors.py
src/dioptra/restapi/v1/shared/drafts/controller.py
src/dioptra/restapi/v1/shared/drafts/schema.py
src/dioptra/restapi/v1/shared/drafts/service.py
src/frontend/src/dialogs/QueueDraftDialog.vue
src/frontend/src/services/dataApi.ts
src/frontend/src/views/QueuesView.vue
tests/unit/restapi/lib/asserts.py
tests/unit/restapi/lib/routines.py

This commit adds an optional query parameter for changing a draft modifications base snapshot ID to the PUT endpoint. If a snapshot ID is provided the value is updated, otherwise it is left unchanged.
This feature is designed to enable the reconciliation of drafts by allowing the user to signal that their changes are based on a more recent snapshot.
An existing test is modified to test this feature.

feat(restapi): add snapshot id to draft modifications PUT endpoints

---

src/frontend/src/App.vue
src/frontend/src/assets/main.css
src/frontend/src/components/SnapshotList.vue
src/frontend/src/components/TableComponent.vue
src/frontend/src/dialogs/DialogComponent.vue
src/frontend/src/dialogs/LeaveFormDialog.vue
src/frontend/src/dialogs/QueueDialog.vue
src/frontend/src/router/index.ts
src/frontend/src/stores/LoginStore.ts
src/frontend/src/views/CreateExperiment.vue
src/frontend/src/views/CreateJob.vue

Add ability for user to browse Experiment history in the edit form.  Clicking the toggle will bring out the right drawer containing the snapshot list, which can eventually be used in other form pages.  Selecting a row loads the values into the form.  Up/down keyboard navigation should work when you are clicked into the table.  Table can be sorted.  The queue dialog was also updated to use this SnapshotList component.

feat: browse experiment history

---

tests/unit/restapi/lib/mock_mlflow.py

This should fix at least one of the scenarios that could cause #724, by ensuring that we choose the metric most recently added to the list if two of them have the same timestamp.

fix: choose latest added metric if their timestamps are the same

---

cookiecutter-templates/cookiecutter-dioptra-deployment/{{cookiecutter.__project_slug}}/config/nginx/http_restapi.conf
tests/unit/restapi/lib/mock_mlflow.py

a26566b inadvertently undid changes from 17ded57 and e44c2f6.  This commit reverts the changes back.

fix: revert undesired changes

---

src/dioptra/client/workflows.py
src/dioptra/restapi/v1/shared/signature_analysis.py
src/dioptra/restapi/v1/workflows/controller.py
src/dioptra/restapi/v1/workflows/schema.py
src/dioptra/restapi/v1/workflows/service.py
tests/unit/restapi/test_signature_analysis.py
tests/unit/restapi/v1/workflows/signature_analysis/sample_test_alias.py
tests/unit/restapi/v1/workflows/signature_analysis/sample_test_complex_type.py
tests/unit/restapi/v1/workflows/signature_analysis/sample_test_function_type.py
tests/unit/restapi/v1/workflows/signature_analysis/sample_test_none_return.py
tests/unit/restapi/v1/workflows/signature_analysis/sample_test_optional.py
tests/unit/restapi/v1/workflows/signature_analysis/sample_test_pyplugs_alias.py
tests/unit/restapi/v1/workflows/signature_analysis/sample_test_real_world.py
tests/unit/restapi/v1/workflows/signature_analysis/sample_test_redefinition.py
tests/unit/restapi/v1/workflows/signature_analysis/sample_test_register_alias.py
tests/unit/restapi/v1/workflows/signature_analysis/sample_test_type_conflict.py
tests/unit/restapi/v1/workflows/test_signature_analysis.py

feat(restapi): added signature analysis workflow endpoint & tests

---

src/frontend/src/dialogs/AddTagsDialog.vue
src/frontend/src/dialogs/ModelsDialog.vue
src/frontend/src/dialogs/PluginDialog.vue
src/frontend/src/dialogs/PluginParamsDialog.vue
src/frontend/src/dialogs/QueueDialog.vue
src/frontend/src/views/CreateEntryPoint.vue
src/frontend/src/views/CreateExperiment.vue

This GUI change sets the group field on the different resource creation pages to automatically populate with the user's group.

(GUI) Set a new resource's default group selection to the user's group

---

src/dioptra/restapi/db/alembic/versions/0ca6eca33569_upgrade_resource_snapshot_types.py
tests/unit/restapi/lib/db/setup.py

The code changes fixes #474 and has up-/down-grade logic for alembic up-/down-grades

Db up downgrade snapshot

---

src/dioptra/client/base.py
src/dioptra/client/sessions.py
tests/unit/restapi/lib/client.py

feat(client): add restapi error message to exceptions raised by client

---

src/frontend/src/components/SnapshotList.vue
src/frontend/src/components/TableComponent.vue
src/frontend/src/router/index.ts
src/frontend/src/views/CreateEntryPoint.vue
src/frontend/src/views/CreateExperiment.vue
src/frontend/src/views/JobDashboardView.vue

Closes #848 
When clicking on the experiment or entrypoint link on the job dashboard page...
- The resource page that opens should be read-only
- The specific snapshot used when the job ran should be displayed
- The existing history toggle and snapshot sidebar are used

feat: links to experiment/entrypoint on job dashboard should be snapshot specific

---

src/dioptra/restapi/db/repository/utils/checks.py
tests/unit/restapi/test_experiment_repository.py
tests/unit/restapi/test_queue_repository.py
tests/unit/restapi/test_type_repository.py
tests/unit/restapi/v1/workflows/test_resource_import.py

This commit allows for new resources and resource snapshots to be created with the name of a previously deleted resource. It applies to resources that are using the new repository pattern implementations, reverting the behavior back to how name conflicts were previously handled.
It fixes the issue where if a resource was deleted, that resource's name could never be used again. This issue was especially prevalent when using the resource import workflow to overwrite (delete and re-create) existing resources.
It updates a resource import workflow test by first creating resources with conflicting names before importing resources with the overwrite strategy.

fix(restapi): allow name conflicts with deleted resources/snapshots

---

docs/source/reference/resource-search-language-reference.rst
src/dioptra/restapi/db/repository/utils/search.py
src/dioptra/restapi/v1/shared/search_parser.py
src/frontend/src/components/TableComponent.vue
src/frontend/src/notify.ts
src/frontend/src/services/dataApi.ts

Closes #859 
There already is a 300ms debounce on the search field.  The issue is that when searching with a colon, it naturally takes longer and thus you see the error.  The same issue happens when using a comma.  The fix in this PR is to pass in an empty string whenever the last character of the search is a colon.  Similarly if the last character is a comma, it will strip out that trailing comma.  Now the user wont see an error until they finish typing their search.  I'm not sure this workaround is better because it gives the user a technically wrong result and assume they're gonna continue typing after the colon or comma, but let me know what you think.  Another idea is to have an "advanced search" button next to the search field which brings up a modal where you build these more …

fix: avoid error if last character of search is colon or comma

---

pyproject.toml
src/dioptra/restapi/v1/artifacts/service.py
src/dioptra/restapi/v1/entrypoints/service.py
src/dioptra/restapi/v1/models/service.py
src/dioptra/restapi/v1/plugins/service.py
src/dioptra/restapi/v1/shared/search_parser.py
tests/unit/restapi/test_type_repository.py
tests/unit/restapi/test_utils.py
tests/unit/restapi/v1/shared/test_search_parser.py
tests/unit/restapi/v1/test_artifact.py
tests/unit/restapi/v1/test_entrypoint.py
tests/unit/restapi/v1/test_model.py
tests/unit/restapi/v1/test_plugin.py

closes #896
In addition to fixing #896 
- moved search parser grammar tests and added additional tests to expand coverage
- updated pyproject.toml so that it will include the tests source code 
- flagging this change for @jkglasbrenner
- adding the tests source code directory makes searching and "find all references" behave better in vscode as vscode uses the settings in pyproject.toml to determine what directories will be used. I am unsure of whether there are other side effects, but everything seems to be ok.

fix: some resources are unable to search by tag (#896)

---

docs/source/reference/task-engine-reference.rst
extra/entrypoints/hello-world.yaml
extra/entrypoints/sklearn-classification.yaml
extra/plugins/artifacts/tasks.py
src/dioptra/sdk/api/artifact.py
src/dioptra/sdk/utilities/run_dioptra_job.py

- Remove name() from ArtifactTaskInterface
- Updated code to use the name of the class in place of the result from name() method
- Updated implementations in extra/plugins/artifacts/tasks.py
- Updated Examples

refactor: remove name method from ArtifactTaskInterface

---

src/dioptra/rq/tasks/run_v1_dioptra_job.py
src/dioptra/sdk/utilities/logging/__init__.py
src/dioptra/sdk/utilities/logging/config.py
src/dioptra/sdk/utilities/logging/filters.py
src/dioptra/sdk/utilities/logging/handlers.py
src/dioptra/worker/dioptra_worker_v1.py
tests/unit/restapi/v1/test_job.py

This update implements real-time log forwarding from the Dioptra workers to the API, enabling jobs to stream their logs for storage and retrieval. The implementation uses a context manager that attaches a custom logging handler during job execution, which buffers log records and periodically sends them to the API's job logging endpoint. The API client is authenticated using the worker credentials that are provided in environment variables and ensures logs are flushed even if jobs terminate unexpectedly.
The forwarding mechanism includes filters to prevent recursive logging loops when the client itself emits logs while sending data to the API, and to exclude noise from third-party libraries. The worker's logging configuration has been updated to use structured logging with proper …

Forward worker job logs to api

---

src/dioptra/restapi/v1/entrypoints/service.py
src/frontend/src/views/CreatePluginFile.vue

closes #921 
- Saving entrypoint with duplicate artifact param names causes 500.  It should raise the same error as when you have duplicate entrypoint param names.
-  In the plugin file form, remove frontend logic that checks for duplicate task names.  From our discussion on the call, the backend should handle most validation errors by itself.

Duplicate artifact param error

---

dev-kb/local-setup/MANUAL.md
dev-kb/local-setup/README.md
dev-kb/local-setup/dev-set.sh
dev-kb/local-setup/run-worker.sh

Added the env-variable as described to the `dev-set.sh` Now the variable defaults to the tensorflow-cpu, but will read the variable value if provided as an -l|--lib option from the CLI-style call or will read it from the environment config file. Tested and verified that the variable propagates to the TMux setup as well

Jk i920 worker env var
