usnistgov/dioptra

examples/pytorch-robust-dpatch/.gitignore, examples/pytorch-robust-dpatch/MLproject, examples/pytorch-robust-dpatch/Makefile, examples/pytorch-robust-dpatch/README.md, examples/pytorch-robust-dpatch/data/download_data.py, examples/pytorch-robust-dpatch/demo.ipynb, examples/pytorch-robust-dpatch/docker-compose.yml, examples/pytorch-robust-dpatch/environment.yml, examples/pytorch-robust-dpatch/initdb.py, examples/pytorch-robust-dpatch/src/attack.py, examples/pytorch-robust-dpatch/task-plugins/dioptra_custom/evaluation/__init__.py, examples/pytorch-robust-dpatch/task-plugins/dioptra_custom/evaluation/import_keras.py, examples/pytorch-robust-dpatch/task-plugins/dioptra_custom/evaluation/tensorflow.py, examples/pytorch-robust-dpatch/task-plugins/dioptra_custom/rcnn/__init__.py, examples/pytorch-robust-dpatch/task-plugins/dioptra_custom/rcnn/load_dataset.py, examples/pytorch-robust-dpatch/task-plugins/dioptra_custom/rcnn/load_model.py, examples/pytorch-robust-dpatch/task-plugins/dioptra_custom/rcnn/robust_dpatch.py, examples/pytorch-robust-dpatch/utils.py
Adding robust dpatch example after refactor for dioptra namespace
=> examples: add robust dpatch demo

examples/pytorch-detectron2-demo/.gitignore, examples/pytorch-detectron2-demo/MLproject, examples/pytorch-detectron2-demo/Makefile, examples/pytorch-detectron2-demo/README.md, examples/pytorch-detectron2-demo/balloon_detection_demo.ipynb, examples/pytorch-detectron2-demo/docker-compose.yml, examples/pytorch-detectron2-demo/environment.yml, examples/pytorch-detectron2-demo/initdb.py, examples/pytorch-detectron2-demo/jupyter/before-notebook.d/install-packages.sh, examples/pytorch-detectron2-demo/road_signs_detection_demo.ipynb, examples/pytorch-detectron2-demo/src/poison_train.py, examples/pytorch-detectron2-demo/src/test.py, examples/pytorch-detectron2-demo/src/train.py, examples/pytorch-detectron2-demo/task-plugins/dioptra_custom/pytorch_d2/__init__.py, examples/pytorch-detectron2-demo/task-plugins/dioptra_custom/pytorch_d2/data_detectron2.py, examples/pytorch-detectron2-demo/task-plugins/dioptra_custom/pytorch_d2/eval_detectron2.py, examples/pytorch-detectron2-demo/task-plugins/dioptra_custom/pytorch_d2/log.py, examples/pytorch-detectron2-demo/task-plugins/dioptra_custom/pytorch_d2/metrics.py, examples/pytorch-detectron2-demo/task-plugins/dioptra_custom/pytorch_d2/registry_mlflow_detectron2.py, examples/pytorch-detectron2-demo/task-plugins/dioptra_custom/pytorch_d2/tasks.py, examples/pytorch-detectron2-demo/task-plugins/dioptra_custom/pytorch_d2/train_detectron2.py, examples/pytorch-detectron2-demo/utils.py, examples/tensorflow-adversarial-patches/demo-imagenet-patches.ipynb
Adding Detectron2 demo (poisoning on Balloon and Road Sign Detection datasets). Cleanup ImageNet patch demo outputs.
=> Dioptra adv detectron demo update

task-plugins/dioptra_builtins/registry/art.py
Adding support for additional arguments, for examples such as the Pixel Threshold example which require them
=> builtins: Update keras classifier wrapper

setup.cfg
=> dependencies: add constraint to sqlalchemy version

CODEREVIEWERS.md, CODE_OF_CONDUCT.md, COMMIT_STYLE_GUIDE.md, CONTRIBUTING.md, CONTRIBUTORS.md
=> Add Contributors guidance for Dioptra

tests/unit/task_plugins/conftest.py, tests/unit/task_plugins/dioptra_builtins/metrics/test_distance.py, tests/unit/task_plugins/dioptra_builtins/metrics/test_performance.py
=> test: add unit tests for the task plugins

tests/unit/task_plugins/dioptra_builtins/random/test_rng.py, tests/unit/task_plugins/dioptra_builtins/random/test_sample.py
=> test: add unit tests for task plugins random directory

tests/unit/task_plugins/dioptra_builtins/artifacts/test_mlflow.py, tests/unit/task_plugins/dioptra_builtins/artifacts/test_utils.py
=> test: add unit tests for artifacts task plugins

examples/scripts/__init__.py, examples/scripts/client.py, examples/scripts/utils.py
Towards resolving #163 and #164, still need to change example notebooks and test changes.
=> Refactor: add tar help function to replace use of make and move utils to scripts folder

.gitignore, src/frontend/README.md
Provided more detailed and comprehensive instructions for configuring and running Dioptra components for frontend development. Added the SQLite database to the .gitignore file.
=> docs: Updated instructions for Frontend development

task-plugins/dioptra_builtins/artifacts/utils.py
Tested this as a custom plugin on the tensorflow-mnist-classifier example.
Closes #127
=> refactor: update tarfile plugin to fix CVE-2007-4559

pyproject.toml, src/dioptra/mlflow_plugins/dioptra_backend.py, src/dioptra/mlflow_plugins/dioptra_clients.py, src/dioptra/pyplugs/_plugins.py, src/dioptra/restapi/experiment/controller.py, src/dioptra/restapi/experiment/model.py, src/dioptra/restapi/experiment/schema.py, src/dioptra/restapi/job/model.py, src/dioptra/restapi/job/schema.py, src/dioptra/restapi/job/service.py, src/dioptra/restapi/queue/controller.py, src/dioptra/restapi/queue/model.py, src/dioptra/restapi/queue/schema.py, src/dioptra/restapi/shared/io_file/service.py, src/dioptra/restapi/shared/rq/service.py, src/dioptra/restapi/task_plugin/controller.py, src/dioptra/restapi/task_plugin/errors.py, src/dioptra/restapi/task_plugin/schema.py, src/dioptra/restapi/task_plugin/service.py, src/dioptra/restapi/user/controller.py, src/dioptra/restapi/user/schema.py, src/dioptra/restapi/utils.py, src/dioptra/sdk/object_detection/bounding_boxes/postprocessing/bounding_boxes_postprocessing.py, tox.ini
This PR makes a mypy config change which causes many more type errors to be found, and fixes many of them.  When I run mypy locally, I still get a few remaining errors:
```
src\dioptra\restapi\task_plugin\service.py:78:42: error: Incompatible types in assignment (expression has type "Optional[List[str]]", variable has type "List[str]")  [assignment]
src\dioptra\restapi\job\service.py:95:34: error: Incompatible types in assignment (expression has type "Optional[Experiment]", variable has type "Experiment")  [assignment]
src\dioptra\restapi\job\service.py:98:24: error: Incompatible types in assignment (expression has type "Optional[Queue]", variable has type "Queue")  [assignment]
Found 3 errors in 2 files (checked 176 source files)
```
We can discuss how to fix these, and any other fixes I …
=> Fix mypy config and type errors

cookiecutter-templates/cookiecutter-dioptra-deployment/hooks/post_gen_project.py
=> Fixes to the cookiecutter post-gen hook script to resolve crashes

cookiecutter-templates/cookiecutter-dioptra-deployment/cookiecutter.json, cookiecutter-templates/cookiecutter-dioptra-deployment/{{cookiecutter.__project_slug}}/docker-compose.init.yml, cookiecutter-templates/cookiecutter-dioptra-deployment/{{cookiecutter.__project_slug}}/init-deployment.sh, cookiecutter-templates/cookiecutter-dioptra-deployment/{{cookiecutter.__project_slug}}/scripts/init-minio.sh
Addresses #207. 
tensorflow-mnist-classifier worked after deployment, deployment runs smoothly once, and re-running the init-deployment.sh script does not crash on the minio section
=> build(deployment): revert minio version to latest and improve minio setup script

examples/task-plugins/dioptra_custom/custom_patch_plugins/defenses_image_preprocessing.py, examples/task-plugins/dioptra_custom/evaluation/mlflow.py, examples/tensorflow-adversarial-patches-legacy/README.md, examples/tensorflow-adversarial-patches-legacy/demo-fruits360-patches.ipynb, examples/tensorflow-adversarial-patches-legacy/demo-imagenet-patches.ipynb, examples/tensorflow-adversarial-patches-legacy/demo-mnist-patches.ipynb, examples/tensorflow-adversarial-patches-legacy/src/MLproject, examples/tensorflow-adversarial-patches-legacy/src/deploy_patch.py, examples/tensorflow-adversarial-patches-legacy/src/gaussian_augmentation.py, examples/tensorflow-adversarial-patches-legacy/src/generate_patch.py, examples/tensorflow-adversarial-patches-legacy/src/infer.py, examples/tensorflow-adversarial-patches-legacy/src/init_model.py, examples/tensorflow-adversarial-patches-legacy/src/jpeg_compression.py, examples/tensorflow-adversarial-patches-legacy/src/spatial_smoothing.py, examples/tensorflow-adversarial-patches-legacy/src/train.py, examples/tensorflow-adversarial-patches-legacy/src/train_on_Fruits360_patched.py, examples/tensorflow-adversarial-patches-legacy/src/train_on_Mnist_patched.py, examples/tensorflow-adversarial-patches/src/deploy_patch.yml, examples/tensorflow-adversarial-patches/src/gaussian_augmentation.yml, examples/tensorflow-adversarial-patches/src/generate_patch.yml, examples/tensorflow-adversarial-patches/src/infer.yml, examples/tensorflow-adversarial-patches/src/jpeg_compression.yml, examples/tensorflow-adversarial-patches/src/spatial_smoothing.yml, examples/tensorflow-adversarial-patches/src/train.yml, examples/tensorflow-adversarial-patches/src/train_on_Fruits360_patched.yml, examples/tensorflow-adversarial-patches/src/train_on_Mnist_patched.yml
=> examples: update adversarial patch example to the task engine

src/dioptra/rq/tasks/run_task_engine.py, tests/unit/rq/tasks/test_run_task_engine.py
=> fix: run task engine jobs in a temporary directory

tests/unit/restapi/conftest.py
=> fix: created pytest fixture to solve mlruns bug

CONTRIBUTING.md, TESTING_GUIDE.md
=> chore: update contributing.md and add new testing_guide.md

src/dioptra/restapi/v0/user/service.py
=> Fix leap year registration error

src/dioptra/restapi/v1/experiments/__init__.py, src/dioptra/restapi/v1/experiments/schema.py
=> feat: added v1 schema for experiments and experiment ref

src/dioptra/restapi/routes.py, src/dioptra/restapi/v1/groups/controller.py, src/dioptra/restapi/v1/groups/schema.py, src/dioptra/restapi/v1/schemas.py
Rebased off most recent dev changes before creating PR.
=> V1 groups schema

src/dioptra/restapi/routes.py, src/dioptra/restapi/v1/users/controller.py, src/dioptra/restapi/v1/users/schema.py
Replacing #438 with PR for branch on `usnistgov/dioptra` instead of fork `pscemama-mitre/dioptra`
=> Add v1 users schema and controller stubs

src/dioptra/restapi/routes.py, src/dioptra/restapi/v1/users/controller.py, src/dioptra/restapi/v1/users/schema.py
Refer to [this pr discussion](https://github.com/usnistgov/dioptra/pull/451) for requested changes from @jkglasbrenner that should be implemented in this pr.
=> V1 users schema fix

src/dioptra/restapi/errors.py, src/dioptra/restapi/v1/plugin_parameter_types/__init__.py, src/dioptra/restapi/v1/plugin_parameter_types/controller.py, src/dioptra/restapi/v1/plugin_parameter_types/errors.py, src/dioptra/restapi/v1/plugin_parameter_types/schema.py, src/dioptra/restapi/v1/plugin_parameter_types/service.py, src/dioptra/restapi/v1/utils.py, tests/unit/restapi/lib/actions.py, tests/unit/restapi/v1/conftest.py, tests/unit/restapi/v1/test_plugin_parameter_type.py
The plugin parameter type unit tests in this PR make use of the fixtures/actions/helpers that were separated out into conftest.py, actions.py and helpers.py.
=> feat: plugin parameter types service layer

src/dioptra/restapi/errors.py, src/dioptra/restapi/v1/groups/controller.py, src/dioptra/restapi/v1/groups/service.py, src/dioptra/restapi/v1/queues/controller.py, src/dioptra/restapi/v1/queues/service.py, src/dioptra/restapi/v1/shared/__init__.py, src/dioptra/restapi/v1/shared/search_parser.py, src/dioptra/restapi/v1/users/controller.py, src/dioptra/restapi/v1/users/service.py, src/dioptra/restapi/v1/utils.py, tests/unit/restapi/v1/conftest.py, tests/unit/restapi/v1/test_group.py, tests/unit/restapi/v1/test_queue.py, tests/unit/restapi/v1/test_user.py
This feature defines Dioptra's REST API query language and provides a parser. It is responsible for validating search query syntax and parsing searches into a list of search terms. It does not perform any further interpretation of search terms or construct queries for the Dioptra database.
=> feat: add a module for defining and parsing the v1 API query language

src/dioptra/restapi/errors.py, src/dioptra/restapi/v1/experiments/controller.py, src/dioptra/restapi/v1/experiments/errors.py, src/dioptra/restapi/v1/experiments/schema.py, src/dioptra/restapi/v1/experiments/service.py, src/dioptra/restapi/v1/utils.py, tests/unit/restapi/lib/actions.py, tests/unit/restapi/v1/conftest.py, tests/unit/restapi/v1/test_experiment.py
The service layer and tests are implemented, but entrypoints are disabled.
=> feat: implement experiments service layer and tests

src/dioptra/restapi/v1/experiments/controller.py, src/dioptra/restapi/v1/groups/controller.py, src/dioptra/restapi/v1/plugin_parameter_types/controller.py, src/dioptra/restapi/v1/plugins/controller.py, src/dioptra/restapi/v1/queues/controller.py, src/dioptra/restapi/v1/queues/service.py, src/dioptra/restapi/v1/schemas.py, src/dioptra/restapi/v1/shared/drafts/controller.py, src/dioptra/restapi/v1/shared/snapshots/__init__.py, src/dioptra/restapi/v1/shared/snapshots/controller.py, src/dioptra/restapi/v1/shared/snapshots/service.py, src/dioptra/restapi/v1/users/controller.py, src/dioptra/restapi/v1/utils.py, tests/unit/restapi/lib/asserts.py, tests/unit/restapi/v1/test_queue.py
This feature implements versions for the Queues endpoint. It includes a generic versions service implementation as well as the controller layer for queues.
Tests for accessing versions of queues have been added to the queues test suite.
=> feat: implemented versions for the v1 Queues endpoint

src/dioptra/restapi/v1/entrypoints/controller.py, src/dioptra/restapi/v1/entrypoints/schema.py, src/dioptra/restapi/v1/plugin_parameter_types/controller.py, src/dioptra/restapi/v1/plugin_parameter_types/service.py, src/dioptra/restapi/v1/utils.py, tests/unit/restapi/v1/test_entrypoint.py, tests/unit/restapi/v1/test_plugin_parameter_type.py
This branch includes drafts, snapshots, tags and the fixed search functionality.
=> V1 plugin parameter types (snapshots/drafts/tags)

src/dioptra/restapi/v1/experiments/service.py, tests/unit/restapi/v1/test_experiment.py
Fixed issues with Experiment Services where Entrypoints were not being appended correctly to Experiments with a GET All.
=> V1 fix experiment service

src/dioptra/restapi/v1/entrypoints/service.py, tests/unit/restapi/v1/test_queue.py
This commit fixes a bug where retrieving an entrypoint that was associated with a queue that has since been deleted resulted in a 404 error. The issue was that queue deletion did not remove the resource dependency association between the queue and any entrypoints.
This fix resolves the issue by:
- Updating the queue service to remove all parents of the queue on deletion
- Adding deletion checks when retrieving queues associated with an entrypoint
- Updating the queue deletion test assert an associated entrypoint can be retrieved and the deleted queue is no longer listed.
Resolves #531
=> fix: queue deletion now removes association with entrypoints

src/dioptra/restapi/db/alembic/versions/fd786b5377d6_add_ml_model_versions_resource.py, src/dioptra/restapi/db/models/ml_models.py
=> fix: remove redundant unique constraint from ml_model_versions table

src/frontend/src/assets/main.css, src/frontend/src/components/CodeEditor.vue, src/frontend/src/components/LoggedInForm.vue, src/frontend/src/components/LoginForm.vue, src/frontend/src/components/NavBar.vue, src/frontend/src/components/PageTitle.vue, src/frontend/src/components/RegisterForm.vue, src/frontend/src/components/TableComponent.vue, src/frontend/src/main.ts, src/frontend/src/views/CreatePluginFile.vue, src/frontend/src/views/GroupsAdminView.vue, src/frontend/src/views/HomeView.vue
When toggling light/dark mode, your preference will be saved to localstorage and will persist when you reload or close and reopen the browser.  This PR also fixes some contrast and styling issues with dark mode.
=> feat: remember light dark mode preference

examples/DEPRECATED-tensorflow-imagenet-resnet50/src/gaussian_augmentation.py, src/dioptra/restapi/v1/artifacts/service.py, src/frontend/src/views/CreateJob.vue, src/frontend/src/views/CreatePluginFile.vue
Split per https://github.com/usnistgov/dioptra/pull/582#pullrequestreview-2225240736
=> Spelling not covered by tests

CODE_OF_CONDUCT.md, CONTRIBUTING.md
Fix broken links raised by issue #602
=> docs: fix broken links

cookiecutter-templates/cookiecutter-dioptra-deployment/{{cookiecutter.__project_slug}}/config/nginx/http_restapi.conf
Fixes the frontend refresh problem raised by issue #579.
=> fix: update nginx conf to fix frontend container refresh error

README.md, docs/source/overview/executive-summary.rst
=> docs: fixed typo and expand risk definition

docs/source/getting-started/running-dioptra.rst
=> docs: set datasets_directory during quickstart

src/dioptra/restapi/v1/shared/rq_service.py, tests/unit/restapi/lib/mock_rq.py
=> fix: fix job_timeout parameter in rq

src/dioptra/restapi/v1/schemas.py, src/dioptra/restapi/v1/utils.py
=> docs: update API docs for paging

src/frontend/package-lock.json, src/frontend/package.json, src/frontend/src/components/JobStatus.vue, src/frontend/src/components/PlotlyGraph.vue, src/frontend/src/services/dataApi.ts, src/frontend/src/views/JobDashboardView.vue
Closes: #742 
This PR adds a re-useable `PlotlyGraph` component that is used in the metrics tab of the job dashboard.  This and dev has many newly updated packages.  Please do `npm install` or better yet `npm ci` for a clean install.
=> feat: Plotly graph, updated

src/dioptra/restapi/v1/jobs/schema.py, tests/unit/restapi/lib/actions.py, tests/unit/restapi/test_utils.py, tests/unit/restapi/v1/conftest.py, tests/unit/restapi/v1/test_artifact.py, tests/unit/restapi/v1/test_entrypoint.py, tests/unit/restapi/v1/test_experiment.py, tests/unit/restapi/v1/test_group.py, tests/unit/restapi/v1/test_job.py, tests/unit/restapi/v1/test_model.py, tests/unit/restapi/v1/test_plugin.py, tests/unit/restapi/v1/test_plugin_parameter_type.py, tests/unit/restapi/v1/test_queue.py, tests/unit/restapi/v1/test_tag.py, tests/unit/restapi/v1/test_user.py
Address the test sort issue as described in #772
=> Test resource sort sometimes fails

src/dioptra/client/workflows.py, src/dioptra/restapi/errors.py, src/dioptra/restapi/v1/shared/task_engine_yaml/__init__.py, src/dioptra/restapi/v1/shared/task_engine_yaml/protocols.py, src/dioptra/restapi/v1/shared/task_engine_yaml/service.py, src/dioptra/restapi/v1/workflows/controller.py, src/dioptra/restapi/v1/workflows/lib/export_task_engine_yaml.py, src/dioptra/restapi/v1/workflows/lib/package_job_files.py, src/dioptra/restapi/v1/workflows/lib/views.py, src/dioptra/restapi/v1/workflows/schema.py, src/dioptra/restapi/v1/workflows/service.py, tests/unit/restapi/v1/conftest.py, tests/unit/restapi/v1/workflows/test_entrypoint_validation.py
=> Add validateEntrypoint workflow

src/dioptra/restapi/v1/artifacts/service.py, src/dioptra/restapi/v1/entrypoints/service.py, src/dioptra/restapi/v1/jobs/service.py, src/dioptra/restapi/v1/plugin_parameter_types/service.py, src/dioptra/restapi/v1/plugins/service.py, src/dioptra/restapi/v1/workflows/service.py, src/dioptra/sdk/object_detection/data/annotations/pascal_voc.py, src/dioptra/task_engine/error_message.py
Addresses #864 (partially).  The aforementioned issue shows mypy typing errors in various parts of the codebase.  Most were in parts I did not write, but one was in the task engine area, which I did write.  So I thought I should contribute a fix for that.
=> fix: fix new mypy error in task_engine/error_message.py

docs/source/index.rst, docs/source/reference/resource-search-language-reference.rst
=> docs: add documentation for GET query language

src/dioptra/restapi/errors.py, src/dioptra/restapi/v1/shared/task_engine_yaml/service.py, src/dioptra/restapi/v1/workflows/service.py, src/frontend/src/dialogs/InfoPopupDialog.vue, src/frontend/src/services/dataApi.ts, src/frontend/src/views/CreateEntryPoint.vue
closes #857 
Add validate inputs button to entrypoint create/edit page.  List errors in a popup dialog if there are any.
=> feat: Validate entrypoint button

src/dioptra/restapi/errors.py, src/dioptra/restapi/v1/jobs/service.py
=> fix: provide invalid job parameters to user

src/dioptra/restapi/v1/artifacts/controller.py, src/dioptra/restapi/v1/artifacts/service.py, src/dioptra/restapi/v1/plugins/service.py, tests/unit/restapi/lib/actions.py, tests/unit/restapi/lib/mock_mlflow.py, tests/unit/restapi/v1/conftest.py, tests/unit/restapi/v1/test_artifact.py
=> fix: add additional testing for artifacts

src/dioptra/restapi/v1/artifacts/schema.py, src/dioptra/restapi/v1/utils.py, tests/unit/restapi/v1/test_artifact.py
=> refactor: updates Artifact response to include more information on Task

src/frontend/src/views/CreateJob.vue
Allow user to select artifact snapshot when creating job
=> Job form artifacts

src/dioptra/restapi/v1/workflows/service.py
=> fix: handle null artifact graph in import workflow

src/dioptra/restapi/v1/artifacts/service.py, src/frontend/src/components/NavBar.vue, src/frontend/src/components/TableComponent.vue, src/frontend/src/views/ArtifactsView.vue, src/frontend/src/views/CreateEntryPoint.vue, src/frontend/src/views/CreateJob.vue, src/frontend/src/views/CreatePluginFile.vue, src/frontend/src/views/EditArtifactView.vue, src/frontend/src/views/JobDashboardView.vue
Closes first 4 checkboxes of #971.  
Job and artifact page cleanup
=> feat: clean up job and artifact pages
